### ISSUE TITLE
module 'pyshorteners' has no attribute 'Shortener'

### ISSUE THREAD

**Issue by subutux** [ellisonleao/pyshorteners#117]
**Describe the bug**
While running the example code, I get:
```
AttributeError: module 'pyshorteners' has no attribute 'Shortener'
```

**To Reproduce**
1. sudo pip3 install pyshorteners
2. sudo pip3 freeze | grep pyshorteners
> pyshorteners==0.6.1
3. exec 'python3' & run the example code
```
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshorteners
>>> 
>>> s = pyshorteners.Shortener()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyshorteners' has no attribute 'Shortener'
```

**Expected behavior**
Able to use the Shortener class

**Desktop (please complete the following information):**
 - OS: Linux Fedora 29, Python 3.7.2

**Comment by alifhughes** [comment]
I am also getting the same thing with the same version of Python

**Comment by ellisonleao** [comment]
Sorry guys, latest version is not yet on pypi and current doc is only for the version here on github. For previous versions you can use:

```python
import pyshorteners
# kwargs can be api_key or some required param for a specific url shortener
s = pyshorteners.Shortener('NameOfTheShortener', **kwargs)
s.short('http://thelink')
```

For `NameOfTheShortener` there is an old list, where you can get from the `Shorteners` class enum names. To get the list of names you can use, type:

```python
import pyshorteners
print(['Shorteners.{}'.format(i) for i in dir(pyshorteners.Shorteners) if not i.startswith('__')])
```

Sorry about the mess, i am trying to simplify the api on the 1.0 version which is coming soon

**Comment by shardede** [comment]
I have the code:

```
import pyshorteners
s = pyshorteners.Shortener()
url = ....
shorturl = s.tinyurl.short(url)

```
I am getting the error:

`AttributeError: 'Shortener' object has no attribute 'tinyurl'`

I don't have the problem when running from my windows PC, but only when I run on the cloud (pythonanywhere). But I have installed the module; when I use the code you provide above, I get the output:

`['Shorteners.ADFLY', 'Shorteners.AWSM', 'Shorteners.BITLY', 'Shorteners.CHILPIT', 'Shorteners.CLCKRU', 'Shorteners.DAGD', 'Shorteners.GOOGLE', 'Shorteners.ISGD', 'Shorteners.OSDB', 'Shorteners.OWLY', 'Shorteners.QPSRU', 'Shorteners.QRCX', 'Shorteners.READABILITY', 'Shorteners.SENTALA', 'Shorteners.SIMPLE', 'Shorteners.TINYURL', 'Shorteners.WPACO']`

**Comment by ellisonleao** [comment]
@shardede you are trying to use the new API with the old version. Can you try the steps i've tried and let me know how did it go?

**Comment by ellisonleao** [comment]
@shardede can you change

```
s = pyshorteners.Shortener('tinyurl')
shorturl = s.short('http://www.cnn.com')
```

to

```
import pyshorteners
from pyshorteners import Shorteners
s = pyshorteners.Shortener(Shorteners.TINYURL)
shorturl = s.short('http://www.cnn.com')
print(shorturl)
```

**Comment by shardede** [comment]
Perfect! Thank you so much!

**Comment by ellisonleao** [comment]
Closing this issue. If we have more questions feel free to ask in another one. Thanks!

**Comment by SumedhaZestl** [comment]
>>> import pyshorteners
>>> from pyshorteners import Shorteners
>>> s = pyshorteners.Shortener(Shorteners.TINYURL)
>>> shorturl = s.short('http://www.cnn.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sumedha/.local/lib/python2.7/site-packages/pyshorteners/shorteners/__init__.py", line 115, in short
    self.shorten = self._class(**self.kwargs).short(url)
  File "/home/sumedha/.local/lib/python2.7/site-packages/pyshorteners/shorteners/tinyurl.py", line 13, in short
    response = self._get(self.api_url, params=dict(url=url))
  File "/home/sumedha/.local/lib/python2.7/site-packages/pyshorteners/shorteners/base.py", line 25, in _get
    timeout=self.kwargs['timeout'])
  File "/home/sumedha/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sumedha/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sumedha/.local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sumedha/.local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sumedha/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=0.5)

**Comment by Mohammad2002-web** [comment]
2 days and I still try to solve this problem

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "shortUrl.py", line 60, in <lambda>
  File "shortUrl.py", line 4, in short_url
  File "pyshorteners\__init__.py", line 32, in __init__
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyshorteners.shorteners'


This problem shows when I convert the file .py to .exe file 
please who can help me, thanks in advanced
