### ISSUE TITLE
Tiny.cc shortener fails with exception

### ISSUE THREAD

**Issue by carlosgnet** [ellisonleao/pyshorteners#162]
**Describe the bug**
Calling the Tiny.cc shortener method as per https://pyshorteners.readthedocs.io/en/latest/apis.html#tiny-cc returns an exception. I have tried the api_key and user using Postman and they work correctly.

**To Reproduce**
```
>>> import pyshorteners
>>> url = "http://www.google.com"
>>> url_shortener = pyshorteners.Shortener(api_key = "********-****-****-****-************", login = "********")
>>> short_url = url_shortener.tinycc.short(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carlos/.local/lib/python3.6/site-packages/pyshorteners/shorteners/tinycc.py", line 60, in short
    data = response.json()
  File "/home/carlos/.local/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
200 OK

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
 - Python: 3.6.9

**Comment by carlosgnet** [comment]
Any update on this? Do you need more information or some logs? Thanks.
