### ISSUE TITLE
Could not find a version that satisfies the requirement pyshorteners

### ISSUE THREAD

**Issue by wangyishuai007** [ellisonleao/pyshorteners#34]
**error:**
>\>>[root@linux2 www]# pip install pyshorteners==0.5.5 -v
Collecting pyshorteners==0.5.5
  Getting page https://pypi.python.org/simple/pyshorteners/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pyshorteners/ HTTP/1.1" 404 28063
  Could not fetch URL https://pypi.python.org/simple/pyshorteners/: 404 Client Error: Not Found - skipping
  1 location(s) to search for versions of pyshorteners:
  \* https://pypi.python.org/simple/pyshorteners/
  Getting page https://pypi.python.org/simple/pyshorteners/
  "GET /simple/pyshorteners/ HTTP/1.1" 404 28063
  Could not fetch URL https://pypi.python.org/simple/pyshorteners/: 404 Client Error: Not Found - skipping
  Could not find a version that satisfies the requirement pyshorteners==0.5.5 (from versions: )
Cleaning up...
No matching distribution found for pyshorteners==0.5.5
Exception information:
Traceback (most recent call last):
  File "/root/quokka-env/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/root/quokka-env/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/root/quokka-env/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for pyshorteners==0.5.5

**and**

>\>>[root@linux2 www]# curl -I https://pypi.python.org/simple/pyshorteners/
HTTP/1.1 404 Not Found

how do I do ？

**Comment by ellisonleao** [comment]
Sorry, i've accidentally removed the dist on pypi. Will upload a new one today.

**Comment by ellisonleao** [comment]
@wangyishuai007 just updated a new version. Please try again using pip
