### ISSUE TITLE
go.gl example doesn't work

### ISSUE THREAD

**Issue by jodosh** [ellisonleao/pyshorteners#35]
I installed pyshortners using pip on windows 10. I can use the tinyURL example just fine, but the go.gl example gives the following output

```
Traceback (most recent call last):
  File ".\goglShort.py", line 6, in <module>
    print "My short url is {}".format(shortener.short(url))
  File "C:\Users\USER\Anaconda\lib\site-packages\pyshorteners\shorteners\__init__.py", line 82, in short
    self.shorten = self._class(**self.kwargs).short(url)
  File "C:\Users\USER\Anaconda\lib\site-packages\pyshorteners\shorteners\googl.py", line 35, in short
    'url - {0}'.format(response.content))
pyshorteners.exceptions.ShorteningErrorException: There was an error shortening this url - {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Required",
    "locationType": "parameter",
    "location": "resource.longUrl"
   }
  ],
  "code": 400,
  "message": "Required"
 }
}
```

my sample code is as follows (replacing [MY_API_KEY] with my actual  "Browser key" from my google developers console from a project that has the google URL shortner api enabled): 

```
from pyshorteners import Shortener

url = 'http://www.google.com'
api_key = '[MY_API_KEY]'
shortener = Shortener('GoogleShortener', api_key=api_key)
print "My short url is {}".format(shortener.short(url))

```

Any ideas what I am doing wrong?

**Comment by ellisonleao** [comment]
hey  @jodosh , i willl take a look ASAP. Thanks for sharing

**Comment by jodosh** [comment]
is this a case of PICNIC or did google change their api?

**Comment by ellisonleao** [comment]
Hey @jodosh the issue was fixed and a new version was released on pypi. Can you please upgrade?

```
pip install -U pyshorteners
```

The issue was with the lib itself and not with google. Thanks again for reporting!
