### ISSUE TITLE
Bitly shortener does not return shortened link if it already exists

### ISSUE THREAD

**Issue by Doezer** [ellisonleao/pyshorteners#65]
Hello

I used goo.gl shortener before and didn't have the problem (switched since it's deprecated now). I use bitly but when the script tries shortening an already shortened once URL, it returns an exception without the shortened link.
I have this exception:
```
Traceback (most recent call last):
  File "G:/Prog/Git/owfrdiscordbot/libs/weekly_summary.py", line 301, in create_weekly_summary
    url = api.short(tn.link)
  File "C:\Python36-32\lib\site-packages\pyshorteners\shorteners\__init__.py", line 115, in short
    self.shorten = self._class(**self.kwargs).short(url)
  File "C:\Python36-32\lib\site-packages\pyshorteners\shorteners\bitly.py", line 32, in short
    'url - {0}'.format(response.content))
pyshorteners.exceptions.ShorteningErrorException: There was an error shortening this url - b'ALREADY_A_BITLY_LINK'
```

Which is fine to be raised really, but does it mean I cannot get the link anyway?

edit: seems it's possible to lookup the link with https://dev.bitly.com/links.html#v3_user_link_lookup

**Comment by Doezer** [comment]
I don't want to seem impatient @ellisonleao, could it be possible to review my addition?
Thank you
